module.exports = {
'availableOptions':[
{Name: 'F-Number', Value:  '/main/other/5007'},
{Name: 'shutterspeed', Value:  '/main/capturesettings/shutterspeed'},
{Name: 'iso', Value:  '/main/imgsettings/iso'},
{Name: 'bulb', Value:  '/main/actions/bulb'},
{Name: 'autofocusdrive', Value:  '/main/actions/autofocusdrive'},
{Name: 'manualfocusdrive', Value:  '/main/actions/manualfocusdrive'},
{Name: 'changeafarea', Value:  '/main/actions/changeafarea'},
{Name: 'controlmode', Value:  '/main/actions/controlmode'},
{Name: 'viewfinder', Value:  '/main/actions/viewfinder'},
{Name: 'movie', Value:  '/main/actions/movie'},
{Name: 'opcode', Value:  '/main/actions/opcode'},
{Name: 'datetime', Value:  '/main/settings/datetime'},
{Name: 'recordingmedia', Value:  '/main/settings/recordingmedia'},
{Name: 'cleansensor', Value:  '/main/settings/cleansensor'},
{Name: 'fastfs', Value:  '/main/settings/fastfs'},
{Name: 'capturetarget', Value:  '/main/settings/capturetarget'},
{Name: 'serialnumber', Value:  '/main/status/serialnumber'},
{Name: 'manufacturer', Value:  '/main/status/manufacturer'},
{Name: 'cameramodel', Value:  '/main/status/cameramodel'},
{Name: 'deviceversion', Value:  '/main/status/deviceversion'},
{Name: 'vendorextension', Value:  '/main/status/vendorextension'},
{Name: 'acpower', Value:  '/main/status/acpower'},
{Name: 'batterylevel', Value:  '/main/status/batterylevel'},
{Name: 'minfocallength', Value:  '/main/status/minfocallength'},
{Name: 'maxfocallength', Value:  '/main/status/maxfocallength'},
{Name: 'imagesize', Value:  '/main/imgsettings/imagesize'},
{Name: 'isoauto', Value:  '/main/imgsettings/isoauto'},
{Name: 'whitebalance', Value:  '/main/imgsettings/whitebalance'},
{Name: 'colorspace', Value:  '/main/imgsettings/colorspace'},
{Name: 'dlighting', Value:  '/main/capturesettings/dlighting'},
{Name: 'moviequality', Value:  '/main/capturesettings/moviequality'},
{Name: 'longexpnr', Value:  '/main/capturesettings/longexpnr'},
{Name: 'assistlight', Value:  '/main/capturesettings/assistlight'},
{Name: 'exposurecompensation', Value:  '/main/capturesettings/exposurecompensation'},
{Name: 'flashmode', Value:  '/main/capturesettings/flashmode'},
{Name: 'f-number', Value:  '/main/capturesettings/f-number'},
{Name: 'imagequality', Value:  '/main/capturesettings/imagequality'},
{Name: 'focallength', Value:  '/main/capturesettings/focallength'},
{Name: 'focusmode', Value:  '/main/capturesettings/focusmode'},
{Name: 'focusmode2', Value:  '/main/capturesettings/focusmode2'},
{Name: 'effectmode', Value:  '/main/capturesettings/effectmode'},
{Name: 'expprogram', Value:  '/main/capturesettings/expprogram'},
{Name: 'capturemode', Value:  '/main/capturesettings/capturemode'},
{Name: 'focusmetermode', Value:  '/main/capturesettings/focusmetermode'},
{Name: 'exposuremetermode', Value:  '/main/capturesettings/exposuremetermode'},
{Name: 'shutterspeed2', Value:  '/main/capturesettings/shutterspeed2'},
{Name: 'liveviewafmode', Value:  '/main/capturesettings/liveviewafmode'},
{Name: 'nocfcardrelease', Value:  '/main/capturesettings/nocfcardrelease'},
{Name: 'burstnumber', Value:  '/main/capturesettings/burstnumber'},
{Name: 'whitebiaspresetno', Value:  '/main/capturesettings/whitebiaspresetno'},
{Name: 'applicationmode', Value:  '/main/capturesettings/applicationmode'},
{Name: '5001', Value:  '/main/other/5001'},
{Name: '5003', Value:  '/main/other/5003'},
{Name: '5004', Value:  '/main/other/5004'},
{Name: '5005', Value:  '/main/other/5005'},
{Name: '5008', Value:  '/main/other/5008'},
{Name: '500a', Value:  '/main/other/500a'},
{Name: '500b', Value:  '/main/other/500b'},
{Name: '500c', Value:  '/main/other/500c'},
{Name: '500d', Value:  '/main/other/500d'},
{Name: '500e', Value:  '/main/other/500e'},
{Name: '500f', Value:  '/main/other/500f'},
{Name: '5010', Value:  '/main/other/5010'},
{Name: '5011', Value:  '/main/other/5011'},
{Name: '5013', Value:  '/main/other/5013'},
{Name: '5018', Value:  '/main/other/5018'},
{Name: '501c', Value:  '/main/other/501c'},
{Name: 'd303', Value:  '/main/other/d303'},
{Name: 'd406', Value:  '/main/other/d406'},
{Name: 'd407', Value:  '/main/other/d407'},
{Name: 'd015', Value:  '/main/other/d015'},
{Name: 'd01f', Value:  '/main/other/d01f'},
{Name: 'd032', Value:  '/main/other/d032'},
{Name: 'd037', Value:  '/main/other/d037'},
{Name: 'd05d', Value:  '/main/other/d05d'},
{Name: 'd06b', Value:  '/main/other/d06b'},
{Name: 'd08a', Value:  '/main/other/d08a'},
{Name: 'd08f', Value:  '/main/other/d08f'},
{Name: 'd09c', Value:  '/main/other/d09c'},
{Name: 'd0a0', Value:  '/main/other/d0a0'},
{Name: 'd0a4', Value:  '/main/other/d0a4'},
{Name: 'd0b5', Value:  '/main/other/d0b5'},
{Name: 'd0e0', Value:  '/main/other/d0e0'},
{Name: 'd0e1', Value:  '/main/other/d0e1'},
{Name: 'd0e2', Value:  '/main/other/d0e2'},
{Name: 'd0e3', Value:  '/main/other/d0e3'},
{Name: 'd0e4', Value:  '/main/other/d0e4'},
{Name: 'd100', Value:  '/main/other/d100'},
{Name: 'd101', Value:  '/main/other/d101'},
{Name: 'd102', Value:  '/main/other/d102'},
{Name: 'd10b', Value:  '/main/other/d10b'},
{Name: 'd14e', Value:  '/main/other/d14e'},
{Name: 'd161', Value:  '/main/other/d161'},
{Name: 'd163', Value:  '/main/other/d163'},
{Name: 'd16a', Value:  '/main/other/d16a'},
{Name: 'd1a2', Value:  '/main/other/d1a2'},
{Name: 'd1a3', Value:  '/main/other/d1a3'},
{Name: 'd1a4', Value:  '/main/other/d1a4'},
{Name: 'd1ac', Value:  '/main/other/d1ac'},
{Name: 'd1b5', Value:  '/main/other/d1b5'},
{Name: 'd1f0', Value:  '/main/other/d1f0'},
{Name: 'd1f1', Value:  '/main/other/d1f1'},
{Name: 'd200', Value:  '/main/other/d200'},
{Name: 'd201', Value:  '/main/other/d201'}],

'shutterspeed': [{Choice: '0' ,  data: '0.0002s'},
{Choice: '1' ,  data: '0.0003s'},
{Choice: '2 ', data: '0.0004s'},
{Choice: '3 ', data: '0.0005s'},
{Choice: '4 ', data: '0.0006s'},
{Choice: '5 ', data: '0.0008s'},
{Choice: '6 ', data: '0.0010s'},
{Choice: '7 ', data: '0.0012s'},
{Choice: '8 ', data: '0.0015s'},
{Choice: '9 ', data: '0.0020s'},
{Choice: '10 ', data: '0.0025s'},
{Choice: '11 ', data: '0.0031s'},
{Choice: '12 ', data: '0.0040s'},
{Choice: '13 ', data: '0.0050s'},
{Choice: '14 ', data: '0.0062s'},
{Choice: '15 ', data: '0.0080s'},
{Choice: '16 ', data: '0.0100s'},
{Choice: '17 ', data: '0.0125s'},
{Choice: '18 ', data: '0.0166s'},
{Choice: '19 ', data: '0.0200s'},
{Choice: '20 ', data: '0.0250s'},
{Choice: '21 ', data: '0.0333s'},
{Choice: '22 ', data: '0.0400s'},
{Choice: '23 ', data: '0.0500s'},
{Choice: '24 ', data: '0.0666s'},
{Choice: '25 ', data: '0.0769s'},
{Choice: '26 ', data: '0.1000s'},
{Choice: '27 ', data: '0.1250s'},
{Choice: '28 ', data: '0.1666s'},
{Choice: '29 ', data: '0.2000s'},
{Choice: '30 ', data: '0.2500s'},
{Choice: '31 ', data: '0.3333s'},
{Choice: '32 ', data: '0.4000s'},
{Choice: '33 ', data: '0.5000s'},
{Choice: '34 ', data: '0.6250s'},
{Choice: '35 ', data: '0.7692s'},
{Choice: '36 ', data: '1.0000s'},
{Choice: '37 ', data: '1.3000s'},
{Choice: '38 ', data: '1.6000s'},
{Choice: '39 ', data: '2.0000s'},
{Choice: '40 ', data: '2.5000s'},
{Choice: '41 ', data: '3.0000s'},
{Choice: '42 ', data: '4.0000s'},
{Choice: '43 ', data: '5.0000s'},
{Choice: '44 ', data: '6.0000s'},
{Choice: '45 ', data: '8.0000s'},
{Choice: '46 ', data: '10.0000s'},
{Choice: '47 ', data: '13.0000s'},
{Choice: '48 ', data: '15.0000s'},
{Choice: '49 ', data: '20.0000s'},
{Choice: '50 ', data: '25.0000s'},
{Choice: '51 ', data: '30.0000s'},
{Choice: '52 ', data: 'Time'},
{Choice: '53 ', data: 'Bulb'}],
'FNumber': [{Choice: '0' , data: 'f/5.6'},
{Choice: '1' , data:  'f/6.3'},
{Choice: '2' , data: 'f/7.1'},
{Choice: '3' , data: 'f/8'},
{Choice: '4' , data: 'f/9'},
{Choice: '5' , data: 'f/10'},
{Choice: '6' , data: 'f/11'},
{Choice: '7' , data: 'f/13'},
{Choice: '8' , data: 'f/14'},
{Choice: '9' , data: 'f/16'},
{Choice: '10' , data: 'f/18'},
{Choice: '11' , data: 'f/20'},
{Choice: '12' , data: 'f/22'},
{Choice: '13' , data: 'f/25'},
{Choice: '14' , data: 'f/29'},
{Choice: '15' , data: 'f/32'},
{Choice: '16' , data: 'f/36'}],
'iso':[{'Choice': '0' , data: '100'},
{'Choice': '1' , data: '200'},
{'Choice': '2' , data: '400'},
{'Choice': '3' , data: '800'},
{'Choice': '4' , data: '1600'},
{'Choice': '5' , data: '3200'},
{'Choice': '6' , data: '6400'},
{'Choice': '7' , data: '12800'},
{'Choice': '8' , data: '25600'}]
};
